#encoding: utf-8
Category.create!([
  {title_en: "news", title_ch: "最新消息", content: "<h1 class='title'>最新消息</h1><hr><br><br><ul>針對產護護理相關正面新聞報導。</ul>"},
  {title_en: "service", title_ch: "服務內容", content: "<h1 class='title'> 服務內容 </h1><hr><br><br> <p1>※服務目標： <br>一、本著「全心」、「全意」的理念與宗旨，關懷住民及家屬。 <br>二、本著專業知識，提供專業化人性化有尊嚴的關懷和照護。</p1> <p2><br><br>※服務理念： <br> 一、全心：讓您感覺貼心、讓您感覺安心、讓您感覺放心。 <br> 全意：讓顧客滿意、讓員工得意、讓全體如意。 <br> 二、產婦及新生兒應有被呵護的月子生活。 <br> 三、尊重毎一位住民的個性與自主性。 <br> 四、尊重毎位住民的隱私權。 <br> 五、宗教信仰給人精神上的寄託，尊重毎位住民的宗教信仰。 <br> 六、員工要經常接受專業訓練，以提升專業照護品質。 <br> 七、耐心聆聽及婉轉回答，視毎一位住民為自己的親屬。 <br> 八、環境專業化並鼓勵住民家屬參訪，使住民有家的感覺。 <br> 九、讓毎位住民有健康的身體。 <br> 十、適當的安排各項活動使住民的身心獲得舒解及安適。</p2> <p3><br><br>※本產後護理之家特色介紹<br><br><br> 馥御產後護理之家位於台北市大安區微風商圈，捷運出口3分鐘，生活機能佳。<br>附設廚房，每餐提供熱騰騰營養料理。<br>資深護理人員24小時照護媽媽與寶寶，專業照顧一級棒。<br>特約資深小兒科與婦產科醫師定期診視。<br>定期舉辦媽媽教室提供衛教課程。<br>全區室內建材採防火低甲醛綠建材，合格消防設施與消防通道。<br>每房專屬電動擠乳器<br></p3>"},
  {title_en: "rooms", title_ch: "房型介紹", content: "<h1 class='title'>房型介紹</h1><hr><br><br><div class='introduction_name'>房型介紹</div> <ul class='in_right'> <li class='col-md-9 col-md-offset-3 col-xs-9 col-xs-offset-3 photo_frame'><a href='room1.html'><img height='120' src='/assets/img/0824B-C1_small.jpg' width='187' /> <br /> <span class='room_name'>VIP房</span></a> </li> <li class='col-md-4 col-md-offset-3 col-xs-4 col-xs-offset-3 photo_frame'><a href='room2.html'><img height='120' src='/assets/img/0824B-C2_small.jpg' width='187' /> <br /> <span class='room_name'>尊爵房</span></a> </li> <li class='col-md-4 col-xs-4 photo_frame'><a href='room3.html'><img height='120' src='/assets/img/room_1_small.jpg' width='187' /> <br /> <span class='room_name'>典雅房</span></a> </li> </ul> </div>"},
  {title_en: "medteam", title_ch: "醫療團隊", content: " <h1 class='title'>醫療團隊</h1><hr><br><br> <p1> <div class='doctor_title'>婦產科醫師○○○ 醫師</div> 學歷: ○○○醫學系畢業<br> 經歷: ○○○婦產科主治醫師<br> ○○○科臨床講師<br> ○○○醫院婦產科主任<br> 現任: ○○○婦產科診所 院長<br><br> <div class='doctor_title'>小兒科醫師○○○ 醫師</div> 經歷: 前○○○醫院小兒科主治醫師<br> 前○○○醫院新生兒科主任<br> 中華民國小兒科專科醫師<br> 中華民國新生兒科專科醫師<br> 現任: ○○○診所院長<br> 負責人許慧英 護理師<br> 學歷: ○○○○護理系畢業<br><br> <div class='doctor_title'>兒童發展師</div> 經歷:榮總護理長?年以上經驗<br> 產後護理集團副督導<br> 產後護理集團護理長<br><br> <div class='doctor_title'>產後運動訓練師○○○ 老師</div> 學歷: ○○○○醫技系<br> 國體運動保健科學所運動傷害防護組<br> 經歷: 醫檢師<br> 現任: 大○○○○運動中心指導老師<br> 大產後瘦身指導老師<br><br> </p1>"},
  {title_en: "babycare", title_ch: "寶寶照護", content: " <h1 class='title'>寶寶照護</h1><hr><br><br><ul>馥御產後護理之家提供產後至滿月的寶寶照護，<br>包括新生兒身體評估，臍帶護理，母乳哺餵，<br>沐浴清潔，黃疸檢測等等。<br>嬰兒室獨立動線設計並附隔離區，避免院內交叉感染。<br>特聘資深小兒專科醫師及護理人員定期巡診及專業照護<br> </ul>"},
  {title_en: "mommycare", title_ch: "媽咪照護", content: " <h1 class='title'>媽咪照護</h1><hr><br><br> <ul>馥御產後護理之家提供產後至滿月的媽媽照護，包括傷口護理，乳房護理，<br>母乳哺餵，餐食提供，營養指導與新生兒照護指導等等。<br><br> 特聘資深婦產科專科醫師定期巡診及專業照護。<br> 特聘資深瑜珈老師授課，指導媽媽產後骨盆運動，調整體態，快樂迎接新生命到來。<br> </ul>"},
  {title_en: "reservation", title_ch: "預約參觀", content: " <h1 class='title'>預約參觀</h1><hr><br><br> <p class='descriptions'>捷運忠孝敦化站2號出口步行3分鐘即可到達<br> 地址: 10690 台北市大安區忠孝東路4段221號9樓<br> 連絡電話: 02-877-16-877<br> </p> <iframe src='https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d903.6926775176697!2d121.55235164534935!3d25.04185424725029!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442abc5c62b1c13%3A0xb474aaf69240c8c6!2zTm8uIDIyMSwgU2VjdGlvbiA0LCBaaG9uZ3hpYW8gRWFzdCBSZCwg5b6u6aKo5b-g5a2d6aSoIERhYW4gRGlzdHJpY3QsIFRhaXBlaSBDaXR5LCAxMDY!5e0!3m2!1sen!2stw!4v1412059684696' width='600' height='450' frameborder='0' style='border:0'></iframe>"},
  {title_en: "links", title_ch: "相關連結", content: " <h1 class='title'>相關連結</h1><hr><br><br> <a href='http://www.facebook.com/foryu221' target='_blank'> <img src='/assets/img/logo_400x120.png'>Facebook 粉絲團 </a>"}
])
